# Site
repository: irishev/irishev.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jun-Hyung Park
title: Postdoc Researcher
title2: BK21 FOUR R&E Center for Artificial Intelligence
title3: Korea University
email: irish07@korea.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: junbroP
github_username:  irishev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jun-hyung-park-901a62252
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0002-7900-3743
googlescholar_username: Sx5gM_8AAAAJ
# semanticscholar_username: Jun-Hyung-Park/8289290

# Additional icon links
# additional_links:
# - title: email
#   icon: fas fa-envelope
#   url: mailto:irish07@korea.ac.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: 
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a postdoc researcher in BK21 FOUR R&E Center for Artificial Intelligence at Korea University. I have obtained my Ph.D. in Computer Science and Engineering from Korea University, advised by Prof. SangKeun Lee. I received B.S. in Computer Science and Engineering from Korea University.

  My primary research lies in the area of natural language processing and efficient AI:
  - **Commonsense Reasoning**: Improving the commonsense reasoning capabilities of pre-trained models including language models and multi-modal transformers. Interested in augmenting the models with (implicit) commonsense knowledge by incorporating knowledge graphs and retrieving texts.
  - **Language Models**: Improving the various aspects of language models including effectiveness, efficiency, diversity, multilinguality, etc. Addressing any pipeline of language model development, ranging from pre-training to inference.
  - **Model Compression**: Compressing and accelerating pre-trained models for efficient inference, such as network pruning, quantization, and knowledge distillation.

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        # title: Korea University
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          - #### Korea University
            Ph.D. in Computer Science and Engineering\
            Adviser: <a href="http://dilab.korea.ac.kr">Prof. SangKeun Lee</a>\
            Mar 2018 - Feb 2023

          - #### Korea University
            B.S. in Computer Science and Engineering\
            Mar 2014 - Feb 2028

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        # title: Korea University
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          - #### BK21 FOUR R&E Center for Artificial Intelligence, Korea University
            Postdoc researcher\
            Mar 2023 - Present

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        link: "*: equal contribution"
      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2024"
        description: | # this will include new lines to allow paragraphs
          - #### Coconut: Contextualized Commonsense Unified Transformers for Graph-Based Commonsense Augmentation of Language Models
            **Jun-Hyung Park**, Mingyu Lee, Junho Kim, and SangKeun Lee\
            ACL 2024 Under Review

          - #### Let’s Combine KOPS: Phoneme-Guided Korean Out-of-Vocabulary Processing System
            Nayeon Kim, Eojin Jeon, **Jun-Hyung Park**, Mingyu Kim, and SangKeun Lee\
            ACL 2024 Under Review

          - #### Improving Molecular Property Prediction via Topology-Enhanced Chemical Language Model
            Hyuntae Park, Mingyu Lee, **Jun-Hyung Park**, and SangKeun Lee\
            ACL 2024 Under Review

      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2023"
        description: | # this will include new lines to allow paragraphs
          - #### DIVE: Towards Descriptive and Diverse Visual Commonsense Generation
            **Jun-Hyung Park**\*, Hyuntae Park\*, Youjin Kang, Eojin Jeon, and SangKeun Lee\
            Proceedings of **EMNLP 2023**

          - #### Leap-of-Thought: Accelerating Transformers via Dynamic Token Routing
            Yeachan Kim, Junho Kim, **Jun-Hyung Park**, Mingyu Lee, and SangKeun Lee\
            Proceedings of **EMNLP 2023**

          - #### SMoP: Towards Efficient and Effective Prompt Tuning with Sparse Mixture-of-Prompts
            Joon-Young Choi, Junho Kim, **Jun-Hyung Park**, Wing-Lam Mok, and SangKeun Lee\
            Proceedings of **EMNLP 2023**

          - #### Client-Customized Adaptation for Parameter-Efficient Federated Learning
            Yeachan Kim\*, Junho Kim\*, Wing-Lam Mok, **Jun-Hyung Park** and SangKeun Lee\
            **Findings of ACL 2023**

          - #### Dynamic Structure Pruning for Compressing CNNs
            **Jun-Hyung Park**, Yeachan Kim, Junho Kim, Joon-Young Choi, and SangKeun Lee\
            Proceedings of **AAAI 2023**

      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2022"
        description: | 
          - #### Break it Down into BTS: Basic, Tiniest Subword Units for Korean
            **Jun-Hyung Park**\*, Nayeon Kim\*, Joon-Young Choi, Eojin Jeon, Youjin Kang, and SangKeun Lee\
            Proceedings of **EMNLP 2022**

          - #### Tutoring Helps Students Learn Better: Improving Knowledge Distillation for BERT with Tutor Network
            **Jun-Hyung Park**\*, Junho Kim\*, Mingyu Lee, Wing-Lam Mok, Joon-Young Choi, and SangKeun Lee\
            Proceedings of **EMNLP 2022**

          - #### Efficient Pre-training of Masked Language Model via Concept-based Curriculum Masking
            **Jun-Hyung Park**\*, Mingyu Lee\*, Junho Kim, Kang-Min Kim, and SangKeun Lee\
            Proceedings of **EMNLP 2022**

          - #### Quantized Sparse Training: A Unified Trainable Framework for Joint Pruning and Quantization of DNNs
            **Jun-Hyung Park**, Kang-Min Kim, and SangKeun Lee\
            **ACM TECS** Volume 21, Issue 5

          - #### Learning from Missing Relations: Contrastive Learning with Commonsense Knowledge Graphs for Commonsense Inference
            **Jun-Hyung Park**\*, Yong-Ho Jung\*, Joon-Young Choi, Mingyu Lee, Junho Kim, Kang-Min Kim, and SangKeun Lee\
            **Findings of ACL 2022**

          - #### Examining the Impact of Adaptive Convolution on Natural Language Understanding
            **Jun-Hyung Park**, Byung-Ju Choi, and SangKeun Lee\
            **ESWA** Volume 189

      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2021"
        description: | 
          - #### KOAS: Korean Text Offensiveness Analysis System
            San-Hee Park\*, Kang-Min Kim\*, Seonhee Cho\*, **Jun-Hyung Park**, Hyuntae Park, Hyuna Kim, Seongwon Chung, and SangKeun Lee\
            Proceedings of **EMNLP 2021** (Demo)

      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2020"
        description: | 
          - #### Multi-pretraining for Large-scale Text Classification
            Kang-Min Kim, Bumsu Hyeon, Yeachan Kim, **Jun-Hyung Park**, and SangKeun Lee\
            **Findings of EMNLP 2020**

      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2019"
        description: | 
          - #### meChat: In-device Conversational Photo Sharing Service (demo) 
            Jungho Lee, Woo-Jong Ryu, Yoonjoo Ahn, Song-Eun Lee, Kang-Min Kim, **Jun-Hyung Park**, SangKeun Lee\
            Proceedings of **MobiSys 2019**

          - #### Adaptive Convolution for Text Classification
            Byung-Ju Choi, **Jun-Hyung Park**, and SangKeun Lee\
            Proceedings of **NAACL 2019**

      - layout: top-right
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "2018"
        description: | 
          - #### meChat: In-Device Personal Assistant for Conversational Photo Sharing
            Kang-Min Kim\*, Woo-Jong Ryu\*, **Jun-Hyung Park**, SangKeun Lee\
            **IEEE IC** Volume 23, Issue 2
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        
  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        # title: Korea University
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          - #### DFE624 Introduction to Data Science in Python
            Instructor\
            Fall 2023 at Korea University

          - #### DFE611 Modern Information Retrieval Techniques
            Instructor\
            Spring 2023 at Korea University

  - title: Service # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        # title: Korea University
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          - #### Area Chair
            - ACL (2024)
          - #### Program Committee
            - ACL (2023)
            - AAAI (2023, 2024)
            - EMNLP (2022, 2023)
            - NAACL (2024)
            - IEEE Transactions on Neural Networks and Learning Systems (2024)
            - International Journal of Machine Learning and Cybernetics (2024)

  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role
  # - title: Education
  #   layout: list
  #   content:
  #     - layout: top-right
  #       title: Institution name
  #       sub_title: Qualifications (eg. BA Performing Arts)
  #       caption: Date Range (eg. 2016 - 2019)
  #       quote: >
  #         Short institution or course description (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of qualification
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
